name: flutter_whisper_kit_web
description: "Web implementation of the flutter_whisper_kit plugin, providing
  speech recognition and transcription capabilities using web APIs."
version: 0.3.0
repository: https://github.com/r0227n/flutter_whisper_kit/tree/main/packages/flutter_whisper_kit_web
issue_tracker: https://github.com/r0227n/flutter_whisper_kit/issues
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_whisper_kit:
    path: ../flutter_whisper_kit
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterWhisperKitWebPlugin
        fileName: flutter_whisper_kit_web.dart
  assets:
    - assets/flutter_whisper_kit_web.js
